import {useEffect,useRef,useState} from 'react';
import {Search,X,ChevronDown} from 'lucide-react';
import './CountrySearch.css';
export default function CountrySearch({countries,query,setQuery,onSelect,selected,riskFor,color}){
 const [open,setOpen]=useState(false),[index,setIndex]=useState(-1);
 const root=useRef(null),input=useRef(null);
 const sorted=[...countries].sort((a,b)=>(riskFor(a[1])??Infinity)-(riskFor(b[1])??Infinity)||a[1].name.localeCompare(b[1].name));
 const signature=sorted.map(([id,d])=>`${id}:${riskFor(d)}`).join(',');
 useEffect(()=>setIndex(-1),[query,signature]);
 useEffect(()=>{if(!open)return;const outside=e=>{if(!root.current?.contains(e.target))setOpen(false)};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[open]);
 useEffect(()=>{if(index>=0)root.current?.querySelector(`[data-index="${index}"]`)?.scrollIntoView({block:'nearest'})},[index]);
 const choose=id=>{onSelect(id);input.current?.focus({preventScroll:true});setOpen(false);setIndex(-1)};
 return <div className="search-box country-search" ref={root} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}}><Search size={15}/><input ref={input} role="combobox" aria-label="Search countries by IPC phase" aria-expanded={open} aria-controls="country-risk-list" aria-autocomplete="list" aria-activedescendant={open&&index>=0?`country-option-${sorted[index]?.[0]}`:undefined} value={query} onClick={()=>setOpen(true)} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true)}} placeholder="Choose a country" onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);setIndex(-1)}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);if(sorted.length)setIndex(i=>e.key==='ArrowDown'?(i+1)%sorted.length:(i<=0?sorted.length-1:i-1))}else if(e.key==='Enter'&&open&&index>=0&&sorted[index]){e.preventDefault();choose(sorted[index][0])}}}/>{query&&<button aria-label="Clear search" onClick={()=>{setQuery('');input.current?.focus();setOpen(true)}}><X size={14}/></button>}<button aria-label={open?'Hide countries':'Show countries by IPC phase'} aria-expanded={open} onClick={()=>setOpen(!open)}><ChevronDown size={15} style={{transform:open?'rotate(180deg)':undefined}}/></button>{open&&<div className="country-picker"><div className="country-picker-heading"><span>LOWEST → HIGHEST IPC PHASE</span><span>{sorted.length} countries</span></div><div className="country-options" id="country-risk-list" role="listbox" aria-label="Countries sorted by IPC phase">{sorted.map(([id,d],i)=><button type="button" role="option" aria-selected={id===selected} id={`country-option-${id}`} key={id} data-index={i} tabIndex={-1} className={index===i?'keyboard-active':''} onPointerDown={e=>e.preventDefault()} onClick={()=>choose(id)}><span className="country-option-name"><i style={{background:color(riskFor(d))}}/>{d.name}</span><strong style={{color:color(riskFor(d))}}>{d.phase?`IPC ${d.phase}`:'Unavailable'}</strong></button>)}</div>{!sorted.length&&<p className="country-picker-empty">No countries match your search and risk filter.</p>}<div className="country-picker-foot">Historical district samples · Not national probabilities</div></div>}</div>;
}
