import {ArrowUpRight,TrendingUp,Ship,Landmark,CloudSun,Layers,BrainCircuit,ScanLine,ShieldCheck,ArrowDown} from 'lucide-react';
import './Methodology.css';
const inputs=[
 {Icon:TrendingUp,title:'Market prices',subtitle:'The first sign of pressure',detail:'Compare staple-food prices over time, across markets and against local purchasing power. A price movement starts the investigation; it does not establish a cause.'},
 {Icon:Ship,title:'Trade & supply routes',subtitle:'Connections across borders',detail:'Consider route exposure, inventories, port restrictions and transport costs. A disruption matters only where the country or market is actually exposed.'},
 {Icon:Landmark,title:'Policy & economic events',subtitle:'The wider market context',detail:'Exchange rates, trade policy, conflict or changes in demand may help explain a market shift. The relevant evidence can differ for every country.'},
 {Icon:CloudSun,title:'Production & environment',subtitle:'Conditions behind supply',detail:'Harvest conditions, weather anomalies and production estimates can provide context. Their contribution must be assessed alongside other explanations.'},
 {Icon:Layers,title:'Other emerging evidence',subtitle:'An open set of inputs',detail:'The input set is not fixed. New events, reports and local observations can be added when they are relevant, traceable and reliable.'}
];
export default function Methodology({onExplore}){
 return <section className="method-page"><div className="method-intro"><span className="eyebrow">OUR METHODOLOGY</span><h1>How the outlook takes shape.</h1></div><div className="method-column-labels"><span>01 &nbsp; OBSERVE THE WORLD</span><span>02 &nbsp; CONNECT THE EVIDENCE</span><span>03 &nbsp; ANTICIPATE THE RISK</span></div><div className="method-flow">
 <svg className="flow-wires" viewBox="0 0 1000 480" preserveAspectRatio="none" aria-hidden="true">{[42,141,240,339,438].map((y,i)=><path key={y} d={`M240 ${y} C330 ${y},330 240,410 240`}/>)}{[95,240,385].map(y=><path key={y} d={`M590 240 C675 240,675 ${y},760 ${y}`}/>)}{[42,141,240,339,438].map(y=><circle key={`in-${y}`} className="wire-pulse" r="3"><animateMotion begin="0s" dur="4s" repeatCount="indefinite" calcMode="linear" keyPoints="0;1;1" keyTimes="0;0.5;1" path={`M240 ${y} C330 ${y},330 240,410 240`}/><animate attributeName="opacity" begin="0s" dur="4s" repeatCount="indefinite" calcMode="discrete" values="1;0;0" keyTimes="0;0.5;1"/></circle>)}{[95,240,385].map(y=><circle key={`out-${y}`} className="wire-pulse" r="3" opacity="0"><animateMotion begin="0s" dur="4s" repeatCount="indefinite" calcMode="linear" keyPoints="0;0;1" keyTimes="0;0.5;1" path={`M590 240 C675 240,675 ${y},760 ${y}`}/><animate attributeName="opacity" begin="0s" dur="4s" repeatCount="indefinite" calcMode="discrete" values="0;1;1" keyTimes="0;0.5;1"/></circle>)}</svg>
 <div className="input-stack">{inputs.map(({Icon,title,subtitle})=><div key={title} className="signal-node"><Icon size={20}/><span><strong>{title}</strong><small>{subtitle}</small></span><span className="node-port"/></div>)}</div>
 <ArrowDown className="mobile-flow-arrow" aria-hidden="true"/>
 <div className="model-column"><div className="model-node"><div className="model-orbit"><BrainCircuit size={36} strokeWidth={1.2}/></div><span className="section-kicker">OPENRELIEF MODEL</span><h2>Connect the dots.</h2><div className="model-steps"><span><ScanLine size={14}/> Compare patterns</span><span><Layers size={14}/> Explore explanations</span><span><ShieldCheck size={14}/> Assess uncertainty</span></div><span className="model-status"><i/> Integration in progress</span></div></div>
 <ArrowDown className="mobile-flow-arrow" aria-hidden="true"/>
 <div className="output-stack">{[['729','Sudan',87,'#ee8277'],['566','Nigeria',54,'#e8d985'],['356','India',32,'#b5d6b7']].map(([id,name,risk,tint])=><button className="prediction-node" key={id} onClick={()=>onExplore(id)}><div><span><i style={{background:tint}}/>{name}</span><ArrowUpRight size={16}/></div><strong style={{color:tint}}>{risk}<small>%</small></strong><p>Food insecurity risk</p><footer><span>90-day demo outlook</span><span>EXPLORE</span></footer></button>)}</div>
 </div><div className="method-notes"><span>CONCEPTUAL WORKFLOW · DEMO DATA</span><span>Hypotheses, not proven causes · Model integration pending</span></div></section>;
}
